language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git
  - sudo apt-get install -y python3-pip
  - sudo python3 -m pip install -U pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo python3 -m pip install -r requirements.txt
script: sudo python3 runner.py
notifications:
   slack: pynetscript:3GF5L6jlBvYl9TA5mrcJ87rq
