language: python
before_install:
  - sudo apt-get install -y python3-pip
  - sudo python3 -m pip install -U pip
  - chmod 774 /home/travis/build/pynetscript/o365/runner.py
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - python3 -m pip install -r requirements.txt --ignore-installed 
script: python3 runner.py
notifications:
   slack: pynetscript:3GF5L6jlBvYl9TA5mrcJ87rq
